### ISSUE TITLE
Blade compiler exception after upgrade to v5.8

### ISSUE THREAD

**Issue by mnlm** [laravel/lumen-framework#890]
- Lumen Version: v5.8.1
- PHP Version: 7.2.15

### Description:
After upgrading from v5.7 to v5.8 I get the following error: `ReflectionException: Class blade.compiler does not exist in ../vendor/illuminate/container/Container.php:794`.

This is caused by calling the `Blade::directive()` function as shown below.

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        Blade::directive('test', function ($expression) {
            return "<?php echo 'test'; ?>";
        });
    }
}
```

**Comment by driesvints** [comment]
The `Blade` facade doesn't comes out of the box with Lumen. You'll need to specifically set its alias in your bootstrap file:

```
$app->alias('blade.compiler', Illuminate\View\Compilers\BladeCompiler::class);
```

That should theoretically work.

**Comment by mnlm** [comment]
Thanks for your reply. I set the alias as suggested but the error remains.
```php
// bootstrap/app.php
$app->withFacades();
$app->alias('blade.compiler', Illuminate\View\Compilers\BladeCompiler::class);
```
Something must have changed since v5.7. The `Blade` facade worked fine then, just had to uncomment `$app->withFacades();` in the bootstrap file.

**Comment by driesvints** [comment]
This is the PR that changed the way it was resolved was this one: https://github.com/laravel/framework/pull/25497

You did register the `ViewServiceProvider` manually didn't you? https://github.com/laravel/lumen/blob/38b12bccff7ba009bbc931ac0c5dc5e1d09a98a2/bootstrap/app.php#L82

**Comment by mnlm** [comment]
> You did register the ViewServiceProvider manually didn't you? https://github.com/laravel/lumen/blob/38b12bccff7ba009bbc931ac0c5dc5e1d09a98a2/bootstrap/app.php#L82

I didn't, but adding it doesn't change anything. Still the same error.

```php
// // bootstrap/app.php
$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);
$app->register(Illuminate\View\ViewServiceProvider::class);
```

**Comment by driesvints** [comment]
I can't really help you anymore at this point. Lumen doesn't work with views out of the box so I don't know for sure what's needed to make it work. I suggest you try one of the following support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by driesvints** [comment]
I meant Blade*

**Comment by mnlm** [comment]
Ok, I will keep looking into it. Thanks for your time.

**Comment by Techworker** [comment]
I'm not using facades, but it might help you: I trigger the initialization of the 'view' instance in my `AppServiceProvider::boot()` method to make sure everything is bootstrapped.

Something like:

``` php
<?php

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        app('view');
        app('blade.compiler')->directive('my_directive', function ($expression) {
            return 'my_directive output';
         });
    }
   // ...
```
